import { PromisifyAssertion, Tester } from "@vitest/expect";
import { Plugin } from "@vitest/pretty-format";
import { SnapshotState } from "@vitest/snapshot";

export {
  CancelReason,
  ExtendedContext,
  HookCleanupCallback,
  HookListener,
  OnTestFailedHandler,
  OnTestFinishedHandler,
  RunMode,
  RunnerCustomCase,
  RunnerTask,
  RunnerTaskBase,
  RunnerTaskResult,
  RunnerTaskResultPack,
  RunnerTestCase,
  RunnerTestFile,
  RunnerTestSuite,
  SuiteAPI,
  SuiteCollector,
  SuiteFactory,
  TaskContext,
  TaskCustomOptions,
  TaskMeta,
  TaskState,
  TestAPI,
  TestContext,
  TestFunction,
  TestOptions,
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  it,
  onTestFailed,
  onTestFinished,
  suite,
  test,
} from "vitest3";
export { AfterSuiteRunMeta, ModuleCache } from "vitest3";
export {
  ContextRPC,
  ContextTestEnvironment,
  ResolveIdFunction,
  RunnerRPC,
  RuntimeRPC,
  WorkerGlobalState,
} from "vitest3";
export { RuntimeConfig, SerializedCoverageConfig } from "vitest3";
export {
  Assertion,
  AsymmetricMatchersContaining,
  // ExpectPollOptions,
  ExpectStatic,
  JestAssertion,
} from "vitest3";
export {
  Mock,
  MockContext,
  MockInstance,
  Mocked,
  MockedClass,
  MockedFunction,
  MockedObject,
} from "vitest3";
export { bench } from "vitest3";
export {
  BenchFunction,
  Benchmark,
  BenchmarkAPI,
  BenchmarkResult,
} from "vitest3";
export { ExpectTypeOf, expectTypeOf } from "vitest3";
export {
  SnapshotData,
  SnapshotMatchOptions,
  SnapshotResult,
  SnapshotSerializer,
  SnapshotStateOptions,
  SnapshotSummary,
  SnapshotUpdateState,
  UncheckedSnapshot,
} from "vitest3";
export { ErrorWithDiff, ParsedStack, SerializedError, TestError } from "vitest3";
export { DiffOptions } from "vitest3";
export { assert, should } from "vitest3";
export {
  BenchFactory,
  BenchOptions,
  BenchTask,
  BenchTaskResult,
} from "vitest3";
export {
  ApiConfig,
  ArgumentsType,
  Arrayable,
  AssertType,
  Awaitable,
  BaseCoverageOptions,
  BenchmarkUserOptions,
  BrowserConfigOptions,
  BrowserScript,
  BrowserUI,
  BuiltinEnvironment,
  CSSModuleScopeStrategy,
  CollectLineNumbers,
  CollectLines,
  Constructable,
  Context,
  CoverageIstanbulOptions,
  CoverageOptions,
  CoverageProvider,
  CoverageProviderModule,
  CoverageReporter,
  CoverageV8Options,
  Custom,
  CustomProviderOptions,
  DepsOptimizationOptions,
  DoneCallback,
  Environment,
  EnvironmentOptions,
  EnvironmentReturn,
  File,
  HappyDOMOptions,
  InlineConfig,
  JSDOMOptions,
  ModuleGraphData,
  MutableArray,
  Nullable,
  Pool,
  PoolOptions,
  ProjectConfig,
  ProvidedContext,
  RawErrsMap,
  ReportContext,
  Reporter,
  ResolvedConfig,
  ResolvedCoverageOptions,
  ResolvedTestEnvironment,
  RootAndTarget,
  RuntimeContext,
  SequenceHooks,
  SequenceSetupFiles,
  SerializableSpec,
  SerializedConfig,
  SerializedTestSpecification,
  Suite,
  SuiteHooks,
  Task,
  TaskBase,
  TaskResult,
  TaskResultPack,
  Test,
  TransformModePatterns,
  TransformResultWithSource,
  TscErrorInfo,
  TypecheckConfig,
  UserConfig,
  UserConsoleLog,
  UserWorkspaceConfig,
  Vitest,
  VitestEnvironment,
  VitestRunMode,
  VitestUtils,
  VmEnvironmentReturn,
  WebSocketEvents,
  WebSocketHandlers,
  WebSocketRPC,
  WorkerContext,
  WorkerRPC,
  assertType,
  createExpect,
  expect,
  getRunningMode,
  inject,
  isFirstRun,
  isWatchMode,
  runOnce,
  vi,
  vitest,
} from "vitest3";
